ValueSet: AceInhibitorsATC
Id: 1.2.276.0.76.11.499--20200504224822
Title: "ACE inhibitors ATC"
Description: "ACE inhibitors in the context of Covid-19"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-05-04T22:48:22+02:00"
* ^url = "https://www.netzwerk-universitaetsmedizin.de/fhir/ValueSet/ace-inhibitors-atc"
* ^identifier.use = #official
* ^identifier.system = "http://art-decor.org/ns/oids/vs"
* ^identifier.value = "1.2.276.0.76.11.499"
//* ^version = "1.0.5"
* ^status = #active
* ^experimental = false
* ^publisher = "Charité"
* ^immutable = false
* Atc#C09A "ACE-HEMMER, REIN"
* Atc#C09AA "ACE-Hemmer, rein"
* Atc#C09AA01 "Captopril"
* Atc#C09AA02 "Enalapril"
* Atc#C09AA03 "Lisinopril"
* Atc#C09AA04 "Perindopril"
* Atc#C09AA05 "Ramipril"
* Atc#C09AA06 "Quinapril"
* Atc#C09AA07 "Benazepril"
* Atc#C09AA08 "Cilazapril"
* Atc#C09AA09 "Fosinopril"
* Atc#C09AA10 "Trandolapril"
* Atc#C09AA11 "Spirapril"
* Atc#C09AA12 "Delapril"
* Atc#C09AA13 "Moexipril"
* Atc#C09AA14 "Temocapril"
* Atc#C09AA15 "Zofenopril"
* Atc#C09AA16 "Imidapril"
* Atc#C09B "ACE-HEMMER, KOMBINATIONEN"
* Atc#C09BA "ACE-Hemmer und Diuretika"
* Atc#C09BA01 "Captopril und Diuretika"
* Atc#C09BA02 "Enalapril und Diuretika"
* Atc#C09BA03 "Lisinopril und Diuretika"
* Atc#C09BA04 "Perindopril und Diuretika"
* Atc#C09BA05 "Ramipril und Diuretika"
* Atc#C09BA06 "Quinapril und Diuretika"
* Atc#C09BA07 "Benazepril und Diuretika"
* Atc#C09BA08 "Cilazapril und Diuretika"
* Atc#C09BA09 "Fosinopril und Diuretika"
* Atc#C09BA12 "Delapril und Diuretika"
* Atc#C09BA13 "Moexipril und Diuretika"
* Atc#C09BA15 "Zofenopril und Diuretika"
* Atc#C09BA21 "Captopril und Hydrochlorothiazid"
* Atc#C09BA22 "Enalapril und Hydrochlorothiazid"
* Atc#C09BA23 "Lisinopril und Hydrochlorothiazid"
* Atc#C09BA25 "Ramipril und Hydrochlorothiazid"
* Atc#C09BA26 "Quinapril und Hydrochlorothiazid"
* Atc#C09BA27 "Benazepril und Hydrochlorothiazid"
* Atc#C09BA28 "Cilazapril und Hydrochlorothiazid"
* Atc#C09BA29 "Fosinopril und Hydrochlorothiazid"
* Atc#C09BA33 "Moexipril und Hydrochlorothiazid"
* Atc#C09BA35 "Zofenopril und Hydrochlorothiazid"
* Atc#C09BA54 "Perindopril und Indapamid"
* Atc#C09BA55 "Ramipril und Piretanid"
* Atc#C09BB "ACE-Hemmer und Calciumkanalblocker"
* Atc#C09BB02 "Enalapril und Lercanidipin"
* Atc#C09BB03 "Lisinopril und Amlodipin"
* Atc#C09BB04 "Perindopril und Amlodipin"
* Atc#C09BB05 "Ramipril und Felodipin"
* Atc#C09BB06 "Enalapril und Nitrendipin"
* Atc#C09BB07 "Ramipril und Amlodipin"
* Atc#C09BB10 "Trandolapril und Verapamil"
* Atc#C09BB12 "Delapril und Manidipin"
* Atc#C09BX "ACE-Hemmer, andere Kombinationen"
* Atc#C09BX01 "Perindopril, Amlodipin und Indapamid"
* Atc#C09BX02 "Perindopril und Bisoprolol"
* Atc#C09BX03 "Ramipril, Amlodipin und Hydrochlorothiazid"
* Atc#C09BX04 "Perindopril, Bisoprolol und Amlodipin"
* Atc#C09BX05 "Ramipril und Bisoprolol"