ValueSet: DrugTherapySnomed
Id: pharmacological-therapy-snomed
Title: "Drug Therapy SNOMED"
Description: "Pharmacological therapy in the context of Covid-19, relevant SNOMED-Codes"
* insert Metadata
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-07-22T17:35:36+02:00"
* ^identifier.use = #official
* ^identifier.system = "http://art-decor.org/ns/oids/vs"
* ^identifier.value = "1.2.276.0.76.11.539"
* ^immutable = false
* ^copyright = "This artefact includes content from SNOMED Clinical Terms® (SNOMED CT®) which is copyright of the International Health Terminology Standards Development Organisation (IHTSDO). Implementers of these artefacts must have the appropriate SNOMED CT Affiliate license - for more information contact http://www.snomed.org/snomed-ct/getsnomed-ct or info@snomed.org."
* $sct#768759001 "Product containing steroid (product)"
* $sct#413591007 "Product containing atazanavir (medicinal product)"
* $sct#424096001 "Product containing darunavir (medicinal product)"
* $sct#14728000 "Product containing chloroquine (medicinal product)"
* $sct#83490000 "Product containing hydroxychloroquine (medicinal product)"
* $sct#96138006 "Product containing ivermectin (medicinal product)"
* $sct#134573001 "Product containing lopinavir and ritonavir (medicinal product)"
* $sct#78025001 "Product containing ganciclovir (medicinal product)"
* $sct#386142008 "Product containing oseltamivir (medicinal product)"
* $sct#870518005 "Product containing remdesivir (medicinal product)"
* $sct#35063004 "Product containing ribavirin (medicinal product)"
* $sct#444649004 "Product containing tocilizumab (medicinal product)"
* $sct#763522001 "Product containing sarilumab (medicinal product)"
* $sct#416587008 "Product containing calcineurin inhibitor (product)"
* $sct#416897008 "Product containing tumor necrosis factor alpha inhibitor (product)"
* $sct#430817009 "Product containing interleukin 1 receptor antagonist (product)"
* $sct#703779004 "Product containing ruxolitinib (medicinal product)"
* $sct#73133000 "Product containing colchicine (medicinal product)"
* $sct#768865007 "Product containing interferon (product)"
* $sct#88519001 "Product containing calcifediol (medicinal product)"
* $sct#764877006 "Product containing zinc (medicinal product)"
* $ecrf-parameter-codes#antipyretic "Product containing antipyretic"
* $ecrf-parameter-codes#camostat "Product containing camostat"
* $ecrf-parameter-codes#favipiravir "Product containing favipiravir"
* $ecrf-parameter-codes#convalescent-plasma "Convalescent plasma"
* $ecrf-parameter-codes#steroids-gt "Steroids (> 0.5 mg/kg prednisone equivalents)"
* $ecrf-parameter-codes#steroids-lt "Steroids (<= 0.5 mg/kg prednisone equivalents)"