ValueSet: DrugTherapySnomed
Id: 1.2.276.0.76.11.539--20200722173536
Title: "Drug Therapy SNOMED"
Description: "Pharmacological therapy in the context of Covid-19, relevant SNOMED-Codes"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-07-22T17:35:36+02:00"
* ^url = "https://www.netzwerk-universitaetsmedizin.de/fhir/ValueSet/pharmacological-therapy-snomed"
* ^identifier.use = #official
* ^identifier.system = "http://art-decor.org/ns/oids/vs"
* ^identifier.value = "1.2.276.0.76.11.539"
//* ^version = "1.0.4"
* ^status = #active
* ^experimental = false
* ^publisher = "Charité"
* ^immutable = false
* ^copyright = "This artefact includes content from SNOMED Clinical Terms® (SNOMED CT®) which is copyright of the International Health Terminology Standards Development Organisation (IHTSDO). Implementers of these artefacts must have the appropriate SNOMED CT Affiliate license - for more information contact http://www.snomed.org/snomed-ct/getsnomed-ct or info@snomed.org."
* SNOMED_CT#768759001 "Product containing steroid (product)"
* SNOMED_CT#413591007 "Product containing atazanavir (medicinal product)"
* SNOMED_CT#424096001 "Product containing darunavir (medicinal product)"
* SNOMED_CT#14728000 "Product containing chloroquine (medicinal product)"
* SNOMED_CT#83490000 "Product containing hydroxychloroquine (medicinal product)"
* SNOMED_CT#96138006 "Product containing ivermectin (medicinal product)"
* SNOMED_CT#134573001 "Product containing lopinavir and ritonavir (medicinal product)"
* SNOMED_CT#78025001 "Product containing ganciclovir (medicinal product)"
* SNOMED_CT#386142008 "Product containing oseltamivir (medicinal product)"
* SNOMED_CT#870518005 "Product containing remdesivir (medicinal product)"
* SNOMED_CT#35063004 "Product containing ribavirin (medicinal product)"
* SNOMED_CT#444649004 "Product containing tocilizumab (medicinal product)"
* SNOMED_CT#763522001 "Product containing sarilumab (medicinal product)"
* SNOMED_CT#416587008 "Product containing calcineurin inhibitor (product)"
* SNOMED_CT#416897008 "Product containing tumor necrosis factor alpha inhibitor (product)"
* SNOMED_CT#430817009 "Product containing interleukin 1 receptor antagonist (product)"
* SNOMED_CT#703779004 "Product containing ruxolitinib (medicinal product)"
* SNOMED_CT#73133000 "Product containing colchicine (medicinal product)"
* SNOMED_CT#768865007 "Product containing interferon (product)"
* SNOMED_CT#88519001 "Product containing calcifediol (medicinal product)"
* SNOMED_CT#764877006 "Product containing zinc (medicinal product)"
* ParameterCodeseCRF#antipyretic "Product containing antipyretic"
* ParameterCodeseCRF#camostat "Product containing camostat"
* ParameterCodeseCRF#favipiravir "Product containing favipiravir"
* ParameterCodeseCRF#convalescent-plasma "Convalescent plasma"
* ParameterCodeseCRF#steroids-gt "Steroids (> 0.5 mg/kg prednisone equivalents)"
* ParameterCodeseCRF#steroids-lt "Steroids (<= 0.5 mg/kg prednisone equivalents)"