ValueSet: DrugTherapyATC
Id: 1.2.276.0.76.11.494--20200504201742
Title: "Pharmacological Therapy ATC"
Description: "Pharmacological therapy in the context of Covid-19"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-05-04T20:17:42+02:00"
* ^url = "https://www.netzwerk-universitaetsmedizin.de/fhir/ValueSet/pharmacological-therapy-atc"
* ^identifier.use = #official
* ^identifier.system = "http://art-decor.org/ns/oids/vs"
* ^identifier.value = "1.2.276.0.76.11.494"
//* ^version = "1.0.5"
* ^status = #active
* ^experimental = false
* ^publisher = "Charité"
* ^immutable = false
* Atc#N02B "ANDERE ANALGETIKA UND ANTIPYRETIKA"
* Atc#N02BA "Salicylsäure und Derivate"
* Atc#N02BA01 "Acetylsalicylsäure"
* Atc#N02BA02 "Aloxiprin"
* Atc#N02BA03 "Cholinsalicylat"
* Atc#N02BA04 "Natriumsalicylat"
* Atc#N02BA05 "Salicylamid"
* Atc#N02BA06 "Salsalat"
* Atc#N02BA07 "Ethenzamid"
* Atc#N02BA08 "Morpholinsalicylat"
* Atc#N02BA09 "Dipyrocetyl"
* Atc#N02BA10 "Benorilat"
* Atc#N02BA11 "Diflunisal"
* Atc#N02BA12 "Kaliumsalicylat"
* Atc#N02BA13 "Lysin-Acetylsalicylat"
* Atc#N02BA14 "Guacetisal"
* Atc#N02BA15 "Carbasalat calcium"
* Atc#N02BA16 "Imidazolsalicylat"
* Atc#N02BA19 "Cholin-Magnesium-Tris-Salicylat"
* Atc#N02BA20 "Kombinationen"
* Atc#N02BA51 "Acetylsalicylsäure, Kombinationen exkl. Psycholeptika"
* Atc#N02BA55 "Salicylamid, Kombinationen exkl. Psycholeptika"
* Atc#N02BA57 "Ethenzamid, Kombinationen exkl. Psycholeptika"
* Atc#N02BA59 "Dipyrocetyl, Kombinationen exkl. Psycholeptika"
* Atc#N02BA65 "Carbasalat calcium, Kombinationen exkl. Psycholeptika"
* Atc#N02BA71 "Acetylsalicylsäure, Kombinationen mit Psycholeptika"
* Atc#N02BA75 "Salicylamid, Kombinationen mit Psycholeptika"
* Atc#N02BA77 "Ethenzamid, Kombinationen mit Psycholeptika"
* Atc#N02BA79 "Dipyrocetyl, Kombinationen mit Psycholeptika"
* Atc#N02BB "Pyrazolone"
* Atc#N02BB01 "Phenazon"
* Atc#N02BB02 "Metamizol-Natrium"
* Atc#N02BB03 "Aminophenazon"
* Atc#N02BB04 "Propyphenazon"
* Atc#N02BB05 "Nifenazon"
* Atc#N02BB06 "Phenazonsalicylat"
* Atc#N02BB51 "Phenazon, Kombinationen exkl. Psycholeptika"
* Atc#N02BB52 "Metamizol-Natrium, Kombinationen exkl. Psycholeptika"
* Atc#N02BB53 "Aminophenazon, Kombinationen exkl. Psycholeptika"
* Atc#N02BB54 "Propyphenazon, Kombinationen exkl. Psycholeptika**"
* Atc#N02BB56 "Phenazonsalicylat, Kombinationen exkl. Psycholeptika"
* Atc#N02BB71 "Phenazon, Kombinationen mit Psycholeptika"
* Atc#N02BB72 "Metamizol-Natrium, Kombinationen mit Psycholeptika"
* Atc#N02BB73 "Aminophenazon, Kombinationen mit Psycholeptika"
* Atc#N02BB74 "Propyphenazon, Kombinationen mit Psycholeptika"
* Atc#N02BB76 "Phenazonsalicylat, Kombinationen mit Psycholeptika"
* Atc#N02BE "Anilide"
* Atc#N02BE01 "Paracetamol"
* Atc#N02BE03 "Phenacetin"
* Atc#N02BE04 "Bucetin"
* Atc#N02BE05 "Propacetamol"
* Atc#N02BE51 "Paracetamol, Kombinationen exkl. Psycholeptika"
* Atc#N02BE53 "Phenacetin, Kombinationen exkl. Psycholeptika"
* Atc#N02BE54 "Bucetin, Kombinationen exkl. Psycholeptika"
* Atc#N02BE61 "Paracetamol, Kombinationen mit Coffein"
* Atc#N02BE71 "Paracetamol, Kombinationen mit Psycholeptika"
* Atc#N02BE73 "Phenacetin, Kombinationen mit Psycholeptika"
* Atc#N02BE74 "Bucetin, Kombinationen mit Psycholeptika"
* Atc#N02BG "Andere Analgetika und Antipyretika"
* Atc#N02BG02 "Rimazolium"
* Atc#N02BG03 "Glafenin"
* Atc#N02BG04 "Floctafenin"
* Atc#N02BG05 "Viminol"
* Atc#N02BG06 "Nefopam"
* Atc#N02BG07 "Flupirtin"
* Atc#N02BG08 "Ziconotid"
* Atc#N02BG09 "Methoxyfluran"
* Atc#N02BG10 "Cannabinoide"
* Atc#N02BG11 "Mirogabalin"
* Atc#N02BG12 "Tanezumab"
* Atc#N02BH "Homöopathische und anthroposophische Analgetika und Antipyretika"
* Atc#N02BH01 "Aconitum"
* Atc#N02BH10 "Verschiedene"
* Atc#N02BH20 "Kombinationen"
* Atc#N02BP "Pflanzliche Analgetika und Antipyretika"
* Atc#N02BP01 "Blauer Eisenhut"
* Atc#N02BP02 "Lindenblüten"
* Atc#G01B "ANTIINFEKTIVA/ANTISEPTIKA IN KOMBINATION MIT CORTICOSTEROIDEN"
* Atc#G01BA "Antibiotika und Corticosteroide"
* Atc#G01BA01 "Antibiotika und Corticosteroide"
* Atc#G01BC "Chinolin-Derivate und Corticosteroide"
* Atc#G01BD "Antiseptika und Corticosteroide"
* Atc#G01BD01 "Antiseptika und Corticosteroide"
* Atc#G01BE "Sulfonamide und Corticosteroide"
* Atc#G01BE50 "Sulfonamide und Corticosteroide, Kombinationen mit Antibiotika"
* Atc#G01BF "Imidazol-Derivate und Corticosteroide"
* Atc#H02 "CORTICOSTEROIDE ZUR SYSTEMISCHEN ANWENDUNG"
* Atc#H02A "CORTICOSTEROIDE ZUR SYSTEMISCHEN ANWENDUNG, REIN"
* Atc#H02AA "Mineralocorticoide"
* Atc#H02AA01 "Aldosteron"
* Atc#H02AA02 "Fludrocortison"
* Atc#H02AA03 "Desoxycorton"
* Atc#H02AB "Glucocorticoide"
* Atc#H02AB01 "Betamethason"
* Atc#H02AB02 "Dexamethason"
* Atc#H02AB03 "Fluocortolon"
* Atc#H02AB04 "Methylprednisolon"
* Atc#H02AB05 "Paramethason"
* Atc#H02AB06 "Prednisolon"
* Atc#H02AB07 "Prednison"
* Atc#H02AB08 "Triamcinolon"
* Atc#H02AB09 "Hydrocortison"
* Atc#H02AB10 "Cortison"
* Atc#H02AB11 "Prednyliden"
* Atc#H02AB12 "Rimexolon"
* Atc#H02AB13 "Deflazacort"
* Atc#H02AB14 "Cloprednol"
* Atc#H02AB15 "Meprednison"
* Atc#H02AB17 "Cortivazol"
* Atc#H02AB51 "Betamethason-Depot"
* Atc#H02AB54 "Methylprednisolon-Depot"
* Atc#H02AB56 "Prednisolon-Depot"
* Atc#H02AB58 "Triamcinolon-Depot"
* Atc#H02B "CORTICOSTEROIDE ZUR SYSTEMISCHEN ANWENDUNG, KOMBINATIONEN"
* Atc#H02BX "Corticosteroide zur systemischen Anwendung, Kombinationen"
* Atc#H02BX01 "Methylprednisolon, Kombinationen"
* Atc#H02BX02 "Dexamethason, Kombinationen"
* Atc#H02BX06 "Prednisolon, Kombinationen"
* Atc#H02BX08 "Triamcinolon, Kombinationen"
* Atc#H02BX09 "Betamethason, Kombinationen"
* Atc#H02BX20 "Kombinationen"
* Atc#H02BX21 "Desoxycorton, Kombinationen"
* Atc#H02C "NEBENNIERENHEMMSTOFFE"
* Atc#H02CA "Anticorticosteroide"
* Atc#H02CA01 "Trilostan"
* Atc#H02CA02 "Osilodrostat"
* Atc#H02CA03 "Ketoconazol"
* Atc#M01BA "Antiphlogistika/Antirheumatika in Kombination mit Corticosteroiden"
* Atc#M01BA01 "Phenylbutazon und Corticosteroide"
* Atc#M01BA02 "Dipyrocetyl und Corticosteroide"
* Atc#M01BA03 "Acetylsalicylsäure und Corticosteroide"
* Atc#M01BA04 "Mofebutazon und Corticosteroide"
* Atc#M01BA05 "Oxyphenbutazon und Corticosteroide"
* Atc#M01BA06 "Salicylamid und Corticosteroide"
* Atc#M01BA07 "Metamizol und Corticosteroide"
* Atc#M01BA08 "Kebuzon und Corticosteroide"
* Atc#R03AK "Sympathomimetika in Kombination mit Corticosteroiden oder anderen Mitteln, exkl. Anticholinergika"
* Atc#R03AK01 "Epinephrin und andere Mittel bei obstruktiven Atemwegserkrankungen"
* Atc#R03AK02 "Isoprenalin und andere Mittel bei obstruktiven Atemwegserkrankungen"
* Atc#R03AK03 "Fenoterol und Cromoglicinsäure, Dinatriumsalz"
* Atc#R03AK04 "Salbutamol und Cromoglicinsäure, Dinatriumsalz"
* Atc#R03AK05 "Reproterol und Cromoglicinsäure, Dinatriumsalz"
* Atc#R03AK06 "Salmeterol und Fluticason"
* Atc#R03AK07 "Formoterol und Budesonid"
* Atc#R03AK08 "Formoterol und Beclometason"
* Atc#R03AK09 "Formoterol und Mometason"
* Atc#R03AK10 "Vilanterol und Fluticasonfuroat"
* Atc#R03AK11 "Formoterol und Fluticason"
* Atc#R03AK12 "Salmeterol und Budesonid"
* Atc#R03AK13 "Salbutamol und Beclometason"
* Atc#R03AK14 "Indacaterol und Mometason"
* Atc#R03AL "Sympathomimetika in Kombination mit Anticholinergika inkl. Dreifachkombinationen mit Corticosteroiden"
* Atc#R03AL01 "Fenoterol und Ipratropiumbromid"
* Atc#R03AL02 "Salbutamol und Ipratropiumbromid"
* Atc#R03AL03 "Vilanterol und Umeclidiniumbromid"
* Atc#R03AL04 "Indacaterol und Glycopyrroniumbromid"
* Atc#R03AL05 "Formoterol und Aclidiniumbromid"
* Atc#R03AL06 "Olodaterol und Tiotropiumbromid"
* Atc#R03AL07 "Formoterol und Glycopyrroniumbromid"
* Atc#R03AL08 "Vilanterol, Umeclidiniumbromid und Fluticasonfuroat"
* Atc#R03AL09 "Formoterol, Glycopyrroniumbromid und Beclometason"
* Atc#S02B "CORTICOSTEROIDE"
* Atc#S02BA "Corticosteroide"
* Atc#S02BA01 "Hydrocortison"
* Atc#S02BA03 "Prednisolon"
* Atc#S02BA06 "Dexamethason"
* Atc#S02BA07 "Betamethason"
* Atc#S02BA08 "Fluocinolonacetonid"
* Atc#S02BA56 "Dexamethason, Kombinationen"
* Atc#L04AD "Calcineurin-Inhibitoren"
* Atc#L04AD01 "Ciclosporin"
* Atc#L04AD02 "Tacrolimus"
* Atc#L04AD03 "Voclosporin"
* Atc#L04AB "Tumornekrosefaktor alpha(TNF-alpha)-Inhibitoren"
* Atc#L04AB01 "Etanercept"
* Atc#L04AB02 "Infliximab"
* Atc#L04AB03 "Afelimomab"
* Atc#L04AB04 "Adalimumab"
* Atc#L04AB05 "Certolizumab pegol"
* Atc#L04AB06 "Golimumab"
* Atc#L04AB07 "Opinercept"
* Atc#L04AC "Interleukin-Inhibitoren"
* Atc#L04AC01 "Daclizumab"
* Atc#L04AC02 "Basiliximab"
* Atc#L04AC03 "Anakinra"
* Atc#L04AC04 "Rilonacept"
* Atc#L04AC05 "Ustekinumab"
* Atc#L04AC07 "Tocilizumab"
* Atc#L04AC08 "Canakinumab"
* Atc#L04AC09 "Briakinumab"
* Atc#L04AC10 "Secukinumab"
* Atc#L04AC11 "Siltuximab"
* Atc#L04AC12 "Brodalumab"
* Atc#L04AC13 "Ixekizumab"
* Atc#L04AC14 "Sarilumab"
* Atc#L04AC15 "Sirukumab"
* Atc#L04AC16 "Guselkumab"
* Atc#L04AC17 "Tildrakizumab"
* Atc#L04AC18 "Risankizumab"
* Atc#L04AC19 "Satralizumab"
* Atc#L04AC20 "Netakimab"
* Atc#L04AC21 "Bimekizumab"
* Atc#L03AB "Interferone"
* Atc#L03AB01 "Interferon alfa, natürlich"
* Atc#L03AB02 "Interferon beta, natürlich"
* Atc#L03AB03 "Interferon gamma"
* Atc#L03AB04 "Interferon alfa-2a"
* Atc#L03AB05 "Interferon alfa-2b"
* Atc#L03AB06 "Interferon alfa-n1"
* Atc#L03AB07 "Interferon beta-1a"
* Atc#L03AB08 "Interferon beta-1b"
* Atc#L03AB09 "Interferon alfacon-1"
* Atc#L03AB10 "Peginterferon alfa-2b"
* Atc#L03AB11 "Peginterferon alfa-2a"
* Atc#L03AB12 "Albinterferon alfa-2b"
* Atc#L03AB13 "Peginterferon beta-1a"
* Atc#L03AB14 "Cepeginterferon alfa-2b"
* Atc#L03AB15 "Ropeginterferon alfa-2b"
* Atc#L03AB18 "Interferon gamma-1b"
* Atc#L03AB60 "Peginterferon alfa-2b, Kombinationen"
* Atc#L03AB61 "Peginterferon alfa-2a, Kombinationen"
* Atc#A12CB "Zink"
* Atc#A12CB01 "Zinksulfat"
* Atc#A12CB02 "Zinkgluconat"
* Atc#A12CB03 "Zinkprotein-Komplex"
* Atc#A12CB05 "Zinkhydrogenaspartat"
* Atc#A12CB06 "Zinkorotat"
* Atc#D01AC20 "Imidazole/Triazole in Kombination mit Corticosteroiden"
* Atc#J05AE08 "Atazanavir"
* Atc#J05AR15 "Atazanavir und Cobicistat"
* Atc#J05AR23 "Atazanavir und Ritonavir"
* Atc#J05AE10 "Darunavir"
* Atc#J05AR14 "Darunavir und Cobicistat"
* Atc#J05AR22 "Emtricitabin, Tenofoviralafenamid, Darunavir und Cobicistat"
* Atc#P01BA01 "Chloroquin"
* Atc#P01BA02 "Hydroxychloroquin"
* Atc#P02CF01 "Ivermectin"
* Atc#D11AX22 "Ivermectin"
* Atc#J05AR10 "Lopinavir und Ritonavir"
* Atc#J05AB06 "Ganciclovir"
* Atc#S01AD09 "Ganciclovir"
* Atc#J05AH02 "Oseltamivir"
* Atc#J05AP01 "Ribavirin"
* Atc#B02AB04 "Camostat"
* Atc#J05AX27 "Favipiravir"
* Atc#S01XA18 "Ciclosporin"
* Atc#D11AH01 "Tacrolimus"
* Atc#L04AA10 "Sirolimus"
* Atc#L04AA18 "Everolimus"
* Atc#L01XE10 "Everolimus"
* Atc#L01XE18 "Ruxolitinib"
* Atc#M04AC01 "Colchicin"
* Atc#S01AD05 "Interferon"
* Atc#A11CC06 "Calcifediol"