ValueSet: ImmunoglobulinsATC
Id: 1.2.276.0.76.11.500--20200504225150
Title: "Immunoglobulins ATC"
Description: "Pharmacological therapy using immunoglobulins in the context of Covid-19"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-05-04T22:51:50+02:00"
* ^url = "https://www.netzwerk-universitaetsmedizin.de/fhir/ValueSet/immunoglobulins-atc"
* ^identifier.use = #official
* ^identifier.system = "http://art-decor.org/ns/oids/vs"
* ^identifier.value = "1.2.276.0.76.11.500"
//* ^version = "1.0.5"
* ^status = #active
* ^experimental = false
* ^publisher = "Charité"
* ^immutable = false
* Atc#J06B "IMMUNGLOBULINE"
* Atc#J06BA "Immunglobuline, normal human"
* Atc#J06BA01 "Immunglobuline, normal human, zur extravasalen Anwendung"
* Atc#J06BA02 "Immunglobuline, normal human, zur intravasalen Anwendung"
* Atc#J06BB "Spezifische Immunglobuline"
* Atc#J06BB01 "Anti-D(rh)-Immunglobulin"
* Atc#J06BB02 "Tetanus-Immunglobulin"
* Atc#J06BB03 "Varicella/Zoster-Immunglobulin"
* Atc#J06BB04 "Hepatitis-B-Immunglobulin"
* Atc#J06BB05 "Tollwut-Immunglobulin"
* Atc#J06BB06 "Röteln-Immunglobulin"
* Atc#J06BB07 "Kuhpocken-Immunglobulin"
* Atc#J06BB08 "Staphylococcus-Immunglobulin"
* Atc#J06BB09 "Cytomegalievirus-Immunglobulin"
* Atc#J06BB10 "Diphtherie-Immunglobulin"
* Atc#J06BB11 "Hepatitis-A-Immunglobulin"
* Atc#J06BB12 "FSME-Immunglobulin"
* Atc#J06BB13 "Pertussis-Immunglobulin"
* Atc#J06BB14 "Masern-Immunglobulin"
* Atc#J06BB15 "Mumps-Immunglobulin"
* Atc#J06BB16 "Palivizumab"
* Atc#J06BB17 "Motavizumab"
* Atc#J06BB18 "Raxibacumab"
* Atc#J06BB19 "Anthrax-Immunglobulin"
* Atc#J06BB21 "Bezlotoxumab"
* Atc#J06BB22 "Obiltoxaximab"
* Atc#J06BB30 "Kombinationen"
* Atc#J06BC "Andere Immunglobuline"
* Atc#J06BC01 "Nebacumab"
* Atc#J06BC10 "Andere Immunglobuline"