ValueSet: LaboratoryTestsGECCO
Id: lab-tests-gecco
Title: "Laboratory Tests GECCO"
Description: "Laboratory tests in the context of Covid-19"
* insert Metadata
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-06-05T17:27:13+02:00"
* ^identifier.use = #official
* ^identifier.system = "http://art-decor.org/ns/oids/vs"
* ^identifier.value = "1.2.276.0.76.11.521"
* ^immutable = false
* $loinc#48421-2 "C reactive protein [Mass/volume] in Capillary blood"
* $loinc#71426-1 "C reactive protein [Mass/volume] in Blood by High sensitivity method"
* $loinc#76486-0 "C reactive protein [Moles/volume] in Serum or Plasma by High sensitivity method"
* $loinc#30522-7 "C reactive protein [Mass/volume] in Serum or Plasma by High sensitivity method"
* $loinc#1988-5 "C reactive protein [Mass/volume] in Serum or Plasma"
* $loinc#76485-2 "C reactive protein [Moles/volume] in Serum or Plasma"
* $loinc#20567-4 "Ferritin [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#86914-9 "Ferritin goal [Mass/volume] Serum or Plasma"
* $loinc#14723-1 "Ferritin [Moles/volume] in Serum or Plasma"
* $loinc#2276-4 "Ferritin [Mass/volume] in Serum or Plasma"
* $loinc#24373-3 "Ferritin [Mass/volume] in Blood"
* $loinc#1971-1 "Bilirubin.indirect [Mass/volume] in Serum or Plasma"
* $loinc#1975-2 "Bilirubin.total [Mass/volume] in Serum or Plasma"
* $loinc#14631-6 "Bilirubin.total [Moles/volume] in Serum or Plasma"
* $loinc#59828-4 "Bilirubin.total [Mass/volume] in Venous blood"
* $loinc#59827-6 "Bilirubin.total [Mass/volume] in Arterial blood"
* $loinc#42719-5 "Bilirubin.total [Mass/volume] in Blood"
* $loinc#48066-5 "Fibrin D-dimer DDU [Mass/volume] in Platelet poor plasma"
* $loinc#48065-7 "Fibrin D-dimer FEU [Mass/volume] in Platelet poor plasma"
* $loinc#48067-3 "Fibrin D-dimer FEU [Mass/volume] in Platelet poor plasma by Immunoassay"
* $loinc#55398-2 "Short Fibrin D-dimer FEU and DDU panel - Platelet poor plasma"
* $loinc#71427-9 "Fibrin D-dimer FEU [Mass/volume] in Blood by Immunoassay"
* $loinc#7799-0 "Fibrin D-dimer [Units/volume] in Platelet poor plasma"
* $loinc#91556-1 "Fibrin D-dimer DDU [Mass/volume] in Blood by Immunoassay"
* $loinc#38898-3 "Fibrin D-dimer [Titer] in Platelet poor plasma"
* $loinc#3246-6 "Fibrin D-dimer [Units/volume] in Platelet poor plasma by Immunoassay"
* $loinc#48058-2 "Fibrin D-dimer DDU [Mass/volume] in Platelet poor plasma by Immunoassay"
* $loinc#2325-9 "Gamma glutamyl transferase/Aspartate aminotransferase [Enzymatic activity ratio] in Serum or Plasma"
* $loinc#2324-2 "Gamma glutamyl transferase [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#1920-8 "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#30239-8 "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma by With P-5'-P"
* $loinc#88112-8 "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma by No addition of P-5'-P"
* $loinc#2532-0 "Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#14805-6 "Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma by Pyruvate to lactate reaction"
* $loinc#14804-9 "Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma by Lactate to pyruvate reaction"
* $loinc#14803-1 "Lactate dehydrogenase [Enzymatic activity/volume] in Body fluid by Lactate to pyruvate reaction"
* $loinc#60017-1 "Lactate dehydrogenase [Enzymatic activity/volume] in Body fluid by Pyruvate to lactate reaction"
* $loinc#49563-0 "Troponin I.cardiac [Mass/volume] in Serum or Plasma by Detection limit <= 0.01 ng/mL"
* $loinc#89579-7 "Troponin I.cardiac [Mass/volume] in Serum or Plasma by High sensitivity method"
* $loinc#67151-1 "Troponin T.cardiac [Mass/volume] in Serum or Plasma by High sensitivity method"
* $loinc#6598-7 "Troponin T.cardiac [Mass/volume] in Serum or Plasma"
* $loinc#6597-9 "Troponin T.cardiac [Mass/volume] in Venous blood"
* $loinc#48425-3 "Troponin T.cardiac [Mass/volume] in Blood"
* $loinc#42757-5 "Troponin I.cardiac [Mass/volume] in Blood"
* $loinc#10839-9 "Troponin I.cardiac [Mass/volume] in Serum or Plasma"
* $loinc#76769-9 "Hemoglobin [Mass/volume] in Venous blood by Oximetry"
* $loinc#59260-0 "Hemoglobin [Moles/volume] in Blood"
* $loinc#718-7 "Hemoglobin [Mass/volume] in Blood"
* $loinc#20509-6 "Hemoglobin [Mass/volume] in Blood by calculation"
* $loinc#55782-7 "Hemoglobin [Mass/volume] in Blood by Oximetry"
* $loinc#75928-2 "Hemoglobin [Moles/volume] in Arterial blood"
* $loinc#14775-1 "Hemoglobin [Mass/volume] in Arterial blood by Oximetry"
* $loinc#30313-1 "Hemoglobin [Mass/volume] in Arterial blood"
* $loinc#30350-3 "Hemoglobin [Mass/volume] in Venous blood"
* $loinc#30351-1 "Hemoglobin [Mass/volume] in Mixed venous blood"
* $loinc#30352-9 "Hemoglobin [Mass/volume] in Capillary blood"
* $loinc#76768-1 "Hemoglobin [Mass/volume] in Mixed venous blood by Oximetry"
* $loinc#21232-4 "Creatinine [Mass/volume] in Arterial blood"
* $loinc#38483-4 "Creatinine [Mass/volume] in Blood"
* $loinc#59826-8 "Creatinine [Moles/volume] in Blood"
* $loinc#12190-5 "Creatinine [Mass/volume] in Body fluid"
* $loinc#25386-4 "Creatinine [Moles/volume] in Body fluid"
* $loinc#2160-0 "Creatinine [Mass/volume] in Serum or Plasma"
* $loinc#14682-9 "Creatinine [Moles/volume] in Serum or Plasma"
* $loinc#14118-4 "Lactate [Mass/volume] in Serum or Plasma"
* $loinc#59032-3 "Lactate [Mass/volume] in Blood"
* $loinc#32693-4 "Lactate [Moles/volume] in Blood"
* $loinc#2520-5 "Lactate [Moles/volume] in Cerebral spinal fluid"
* $loinc#19239-3 "Lactate [Moles/volume] in Capillary blood"
* $loinc#19240-1 "Lactate [Moles/volume] in Mixed venous blood"
* $loinc#2518-9 "Lactate [Moles/volume] in Arterial blood"
* $loinc#2519-7 "Lactate [Moles/volume] in Venous blood"
* $loinc#2524-7 "Lactate [Moles/volume] in Serum or Plasma"
* $loinc#30242-2 "Lactate [Mass/volume] in Arterial blood"
* $loinc#27941-4 "Lactate [Mass/volume] in Cerebral spinal fluid"
* $loinc#49498-9 "Leukocytes [#/volume] in Blood by Estimate"
* $loinc#6690-2 "Leukocytes [#/volume] in Blood by Automated count"
* $loinc#804-5 "Leukocytes [#/volume] in Blood by Manual count"
* $loinc#26464-8 "Leukocytes [#/volume] in Blood"
* $loinc#732-8 "Lymphocytes [#/volume] in Blood by Manual count"
* $loinc#731-0 "Lymphocytes [#/volume] in Blood by Automated count"
* $loinc#30364-4 "Lymphocytes [#/volume] in Blood by Flow cytometry (FC)"
* $loinc#26474-7 "Lymphocytes [#/volume] in Blood"
* $loinc#753-4 "Neutrophils [#/volume] in Blood by Manual count"
* $loinc#751-8 "Neutrophils [#/volume] in Blood by Automated count"
* $loinc#26499-4 "Neutrophils [#/volume] in Blood"
* $loinc#16631-4 "aPTT in Blood by Coagulation 1:1 saline"
* $loinc#43734-3 "aPTT in Platelet poor plasma by Coagulation 1:1 saline"
* $loinc#14979-9 "aPTT in Platelet poor plasma by Coagulation assay"
* $loinc#3173-2 "aPTT in Blood by Coagulation assay"
* $loinc#74775-8 "Platelets [#/volume] in Platelet rich plasma by Automated count"
* $loinc#13056-7 "Platelets [#/volume] in Plasma by Automated count"
* $loinc#26516-5 "Platelets [#/volume] in Plasma"
* $loinc#74464-9 "Platelets [#/volume] in Capillary blood by Manual count"
* $loinc#778-1 "Platelets [#/volume] in Blood by Manual count"
* $loinc#49497-1 "Platelets [#/volume] in Blood by Estimate"
* $loinc#777-3 "Platelets [#/volume] in Blood by Automated count"
* $loinc#26515-7 "Platelets [#/volume] in Blood"
* $loinc#6301-6 "INR in Platelet poor plasma by Coagulation assay"
* $loinc#46418-0 "INR in Capillary blood by Coagulation assay"
* $loinc#34714-6 "INR in Blood by Coagulation assay"
* $loinc#76631-1 "Albumin [Mass/volume] in Blood by Bromocresol purple (BCP) dye binding method"
* $loinc#62235-7 "Albumin [Moles/volume] in Serum or Plasma by Bromocresol green (BCG) dye binding method"
* $loinc#62234-0 "Albumin [Moles/volume] in Serum or Plasma by Bromocresol purple (BCP) dye binding method"
* $loinc#61152-5 "Albumin [Mass/volume] in Serum or Plasma by Bromocresol purple (BCP) dye binding method"
* $loinc#61151-7 "Albumin [Mass/volume] in Serum or Plasma by Bromocresol green (BCG) dye binding method"
* $loinc#2862-1 "Albumin [Mass/volume] in Serum or Plasma by Electrophoresis"
* $loinc#1751-7 "Albumin [Mass/volume] in Serum or Plasma"
* $loinc#54347-0 "Albumin [Moles/volume] in Serum or Plasma"
* $loinc#3176-5 "Antithrombin [Moles/volume] in Platelet poor plasma by Chromogenic method"
* $loinc#91120-6 "Antithrombin in Platelet poor plasma by Chromo.no addition of heparin"
* $loinc#3174-0 "Antithrombin [Units/volume] in Platelet poor plasma by Chromogenic method"
* $loinc#27811-9 "Antithrombin actual/normal in Platelet poor plasma by Chromogenic method"
* $loinc#27812-7 "Antithrombin Ag actual/normal in Platelet poor plasma by Immunoassay"
* $loinc#75241-0 "Procalcitonin [Mass/volume] in Serum or Plasma by Immunoassay"
* $loinc#33959-8 "Procalcitonin [Mass/volume] in Serum or Plasma"
* $loinc#44322-6 "Interleukin 6 [Presence] in Serum or Plasma"
* $loinc#26881-3 "Interleukin 6 [Mass/volume] in Serum or Plasma"
* $loinc#49919-4 "Interleukin 6 [Mass/volume] in Cerebral spinal fluid"
* $loinc#49732-1 "Interleukin 6 [Mass/volume] in Body fluid"
* $loinc#33762-6 "Natriuretic peptide.B prohormone N-Terminal [Mass/volume] in Serum or Plasma"
* $loinc#16859-1 "Fibrinogen [Presence] in Platelet poor plasma"
* $loinc#30902-1 "Fibrinogen [Mass/volume] in Platelet poor plasma by Heat denaturation"
* $loinc#48664-7 "Fibrinogen [Mass/volume] in Platelet poor plasma by Coagulation.derived"
* $loinc#3255-7 "Fibrinogen [Mass/volume] in Platelet poor plasma by Coagulation assay"