ValueSet: OrgansForTransplant
Id: organs-for-transplant
Title: "Organs for Transplantation"
Description: "Organs in the context of transplantation"
* insert Metadata
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-04-30T21:38:08+02:00"
* ^identifier.use = #official
* ^identifier.system = "http://art-decor.org/ns/oids/vs"
* ^identifier.value = "1.2.276.0.76.11.479"
* ^immutable = false
* ^copyright = "This artefact includes content from SNOMED Clinical Terms® (SNOMED CT®) which is copyright of the International Health Terminology Standards Development Organisation (IHTSDO). Implementers of these artefacts must have the appropriate SNOMED CT Affiliate license - for more information contact http://www.snomed.org/snomed-ct/getsnomed-ct or info@snomed.org."
* $sct#302509004 "Entire heart (body structure)"
* $sct#181216001 "Entire lung (body structure)"
* $sct#181268008 "Entire liver (body structure)"
* $sct#181414000 "Entire kidney (body structure)"
* $sct#181277001 "Entire pancreas (body structure)"
* $sct#113276009 "Intestinal structure (body structure)"
* $sct#181250005 "Entire small intestine (body structure)"
* $sct#181254001 "Entire large intestine (body structure)"
* $sct#119181002 "Skin part (body structure)"
* $sct#181162001 "Entire cornea (body structure)"
* $sct#41845008 "Ear ossicle structure (body structure)"
* $sct#181285005 "Entire heart valve (body structure)"
* $sct#119206002 "Blood vessel part (body structure)"
* $sct#8935007 "Cerebral meninges structure (body structure)"
* $sct#3138006 "Bone (tissue) structure (body structure)"
* $sct#309312004 "Cartilage tissue (body structure)"
* $sct#13024002 "Tendon structure (body structure)"