ValueSet: VaccinesATC
Id: gecco-valueset-vaccines-atc
Title: "Vaccines ATC"
Description: "This value set contains ATC codes for vaccines"
* ^url = "https://www.netzwerk-universitaetsmedizin.de/fhir/ValueSet/vaccines-atc"
//* ^version = "1.0.5"
* ^status = #active
* ^experimental = false
* ^publisher = "Charité"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "https://www.bihealth.org/en/research/core-facilities/interoperability/"
* ^immutable = false
* Atc#J07AR "Typhus (exanthematicus)-Impfstoff"
* Atc#J07AR01 "Typhus exanthematicus, inaktiviert, ganze Zelle"
* Atc#J07AC "Milzbrand-Impfstoffe"
* Atc#J07AC01 "Anthrax-Antigen"
* Atc#J07AD "Brucellose-Impfstoffe"
* Atc#J07AD01 "Brucella-Antigen"
* Atc#J07AE "Cholera-Impfstoffe"
* Atc#J07AE01 "Cholera, inaktiviert, ganze Zelle"
* Atc#J07AE02 "Cholera, lebend abgeschwächt"
* Atc#J07AE51 "Cholera, Kombinationen mit Typhus-Impfstoff,  inaktiviert, ganze Zelle"
* Atc#J07AF "Diphtherie-Impfstoffe"
* Atc#J07AF01 "Diphtherie-Toxoid"
* Atc#J07AG "Haemophilus influenzae B-Impfstoffe"
* Atc#J07AG01 "Haemophilus influenzae B, gereinigtes Antigen konjugiert"
* Atc#J07AG51 "Haemophilus influenzae B, Kombinationen mit Toxoiden"
* Atc#J07AG52 "Haemophilus influenzae B, Kombinationen mit Pertussis und Toxoiden"
* Atc#J07AG53 "Haemophilus influenzae B, Kombinationen mit  Meningokokken C, konjugiert"
* Atc#J07AH "Meningokokken-Impfstoffe"
* Atc#J07AH01 "Meningokokken A, gereinigtes Polysaccharid-Antigen"
* Atc#J07AH02 "Andere Meningokokken monovalent,  gereinigtes Polysaccharid-Antigen"
* Atc#J07AH03 "Meningokokken bivalent (A, C),  gereinigtes Polysaccharid-Antigen"
* Atc#J07AH04 "Meningokokken tetravalent (A, C, Y, W-135),  gereinigtes Polysaccharid-Antigen"
* Atc#J07AH05 "Andere Meningokokken polyvalent,  gereinigtes Polysaccharid-Antigen"
* Atc#J07AH06 "Meningokokken B, äußere Vesikelmembran-Impfstoff"
* Atc#J07AH07 "Meningokokken C, gereinigtes Polysaccharid-Antigen,  konjugiert"
* Atc#J07AH08 "Meningokokken tetravalent (A, C, Y, W-135),  gereinigtes Polysaccharid-Antigen, konjugiert"
* Atc#J07AH09 "Meningokokken B, Multikomponenten-Impfstoff"
* Atc#J07AH10 "Meningokokken A, gereinigtes Polysaccharid-Antigen,  konjugiert"
* Atc#J07AJ "Pertussis-Impfstoffe"
* Atc#J07AJ01 "Pertussis, inaktiviert, ganze Zelle"
* Atc#J07AJ02 "Pertussis, gereinigtes Antigen"
* Atc#J07AJ51 "Pertussis, inaktiviert, ganze Zelle, Kombinationen mit Toxoiden"
* Atc#J07AJ52 "Pertussis, gereinigtes Antigen, Kombinationen mit Toxoiden"
* Atc#J07AK "Pest-Impfstoffe"
* Atc#J07AK01 "Pest, inaktiviert, ganze Zelle"
* Atc#J07AL "Pneumokokken-Impfstoffe"
* Atc#J07AL01 "Pneumokokken, gereinigtes Polysaccharid-Antigen"
* Atc#J07AL02 "Pneumokokken, gereinigtes Polysaccharid-Antigen, konjugiert"
* Atc#J07AL52 "Pneumokokken, gereinigtes Polysaccharid-Antigen  und Haemophilus influenzae B, konjugiert"
* Atc#J07AM "Tetanus-Impfstoffe"
* Atc#J07AM01 "Tetanus-Toxoid"
* Atc#J07AM51 "Tetanus-Toxoid, Kombinationen mit Diphtherie-Toxoid"
* Atc#J07AM52 "Tetanus-Toxoid, Kombinationen mit Tetanus-Immunglobulin"
* Atc#J07AN "Tuberkulose-Impfstoffe"
* Atc#J07AN01 "Tuberkulose, lebend abgeschwächt"
* Atc#J07AP "Typhus-Impfstoffe"
* Atc#J07AP01 "Typhus, oral, lebend abgeschwächt"
* Atc#J07AP02 "Typhus, inaktiviert, ganze Zelle"
* Atc#J07AP03 "Typhus, gereinigtes Polysaccharid-Antigen"
* Atc#J07AP10 "Typhus, Kombinationen mit Paratyphustypen"
* Atc#J07BA "Encephalitis-Impfstoffe"
* Atc#J07BA01 "FSME, inaktiviert, ganzes Virus"
* Atc#J07BA02 "Encephalitis, japanische, inaktiviert, ganzes Virus"
* Atc#J07BA03 "Encephalitis, japanische, lebend abgeschwächt"
* Atc#J07BB "Influenza-Impfstoffe"
* Atc#J07BB01 "Influenza, inaktiviert, ganzes Virus"
* Atc#J07BB02 "Influenza, inaktiviert, Spaltvirus oder Oberflächenantigen"
* Atc#J07BB03 "Influenza, lebend abgeschwächt"
* Atc#J07BC "Hepatitis-Impfstoffe"
* Atc#J07BC01 "Hepatitis B, gereinigtes Antigen"
* Atc#J07BC02 "Hepatitis A, inaktiviert, ganzes Virus"
* Atc#J07BC03 "Hepatitis A, gereinigtes Antigen"
* Atc#J07BC20 "Kombinationen"
* Atc#J07BD "Masern-Impfstoffe"
* Atc#J07BD01 "Masern, lebend abgeschwächt"
* Atc#J07BD51 "Masern, Kombinationen mit Mumps, lebend abgeschwächt"
* Atc#J07BD52 "Masern, Kombinationen mit Mumps und Röteln,  lebend abgeschwächt"
* Atc#J07BD53 "Masern, Kombinationen mit Röteln, lebend abgeschwächt"
* Atc#J07BD54 "Masern, Kombinationen mit Mumps, Röteln und Varicella,  lebend abgeschwächt"
* Atc#J07BE "Mumps-Impfstoffe"
* Atc#J07BE01 "Mumps, lebend abgeschwächt"
* Atc#J07BF "Poliomyelitis-Impfstoffe"
* Atc#J07BF01 "Poliomyelitis, oral, monovalent, lebend abgeschwächt"
* Atc#J07BF02 "Poliomyelitis, oral, trivalent, lebend abgeschwächt"
* Atc#J07BF03 "Poliomyelitis, trivalent, inaktiviert, ganzes Virus"
* Atc#J07BF04 "Poliomyelitis, oral, bivalent, lebend abgeschwächt"
* Atc#J07BG "Tollwut-Impfstoffe"
* Atc#J07BG01 "Tollwut, inaktiviert, ganzes Virus"
* Atc#J07BH "Rotavirus-Diarrhoe-Impfstoffe"
* Atc#J07BH01 "Rotavirus, lebend abgeschwächt"
* Atc#J07BH02 "Rotavirus, pentavalent, lebend, Reassortanten"
* Atc#J07BJ "Röteln-Impfstoffe"
* Atc#J07BJ01 "Röteln, lebend abgeschwächt"
* Atc#J07BJ51 "Röteln, Kombinationen mit Mumps, lebend abgeschwächt"
* Atc#J07BK "Varicella Zoster Impfstoffe"
* Atc#J07BK01 "Varicella, lebend abgeschwächt"
* Atc#J07BK02 "Zoster Virus, lebend abgeschwächt"
* Atc#J07BK03 "Zoster Virus, gereinigtes Antigen"
* Atc#J07BL "Gelbfieber-Impfstoffe"
* Atc#J07BL01 "Gelbfieber, lebend abgeschwächt"
* Atc#J07BM "Papillomvirus-Impfstoffe"
* Atc#J07BM01 "Humaner-Papillomvirus-Impfstoff (Typen 6,11,16,18)"
* Atc#J07BM02 "Humaner-Papillomvirus-Impfstoff (Typen 16,18)"
* Atc#J07BM03 "Humaner-Papillomvirus-Impfstoff  (Typen 6,11,16,18,31,33,45,52,58)"
* Atc#J07BX "Andere virale Impfstoffe"
* Atc#J07BX01 "Pocken-Impfstoff, lebend, modifiziert"
* Atc#J07BX03 "Covid-19-Impfstoffe"
* Atc#J07CA "Bakterielle und virale Impfstoffe, kombiniert"
* Atc#J07CA01 "Diphtherie-Poliomyelitis-Tetanus"
* Atc#J07CA02 "Diphtherie-Pertussis-Poliomyelitis-Tetanus"
* Atc#J07CA03 "Diphtherie-Röteln-Tetanus"
* Atc#J07CA04 "Haemophilus influenzae B und Poliomyelitis"
* Atc#J07CA05 "Diphtherie-Hepatitis B-Pertussis-Tetanus"
* Atc#J07CA06 "Diphtherie-Haemophilus influenzae  B-Pertussis-Poliomyelitis-Tetanus"
* Atc#J07CA07 "Diphtherie-Hepatitis B-Tetanus"
* Atc#J07CA08 "Haemophilus influenzae B und Hepatitis B"
* Atc#J07CA09 "Diphtherie-Haemophilus influenzae  B-Pertussis-Poliomyelitis-Tetanus-Hepatitis B"
* Atc#J07CA10 "Typhus-Hepatitis A"
* Atc#J07CA11 "Diphtherie-Haemophilus influenzae  B-Pertussis-Tetanus-Hepatitis B"
* Atc#J07CA12 "Diphtherie-Pertussis-Poliomyelitis-Tetanus-Hepatitis B"
* Atc#J07CA13 "Diphtherie-Haemophilus influenzae  B-Pertussis-Tetanus-Hepatitis B-Meningokokken  A + C"