ValueSet: VaccinesSNOMED
Id: vaccines-snomed
Title: "Vaccines SNOMED"
Description: "This value set contains SNOMED codes for vaccines"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-supplement"
* ^extension.valueCanonical = "https://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/snomed-pce-supplement|1.0.5"
* ^url = "https://www.netzwerk-universitaetsmedizin.de/fhir/ValueSet/vaccines-snomed"
* ^status = #active
* ^experimental = false
* ^publisher = "Charité"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "https://www.bihealth.org/en/research/core-facilities/interoperability/"
* ^immutable = false
* ^copyright = "This artefact includes content from SNOMED Clinical Terms® (SNOMED CT®) which is copyright of the International Health Terminology Standards Development Organisation (IHTSDO). Implementers of these artefacts must have the appropriate SNOMED CT Affiliate license - for more information contact http://www.snomed.org/snomed-ct/getsnomed-ct or info@snomed.org."
* $sct#1119305005 "Vaccine product containing only Severe acute respiratory syndrome coronavirus 2 antigen (medicinal product)"
* $sct#1119349007 "Vaccine product containing only Severe acute respiratory syndrome coronavirus 2 messenger ribonucleic acid (medicinal product)"
* $sct#871875004 "Vaccine product containing only Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae antigens (medicinal product)"
* $sct#787859002 "Vaccine product (medicinal product)"
* $sct#37146000 "Typhus vaccine (product)"
* $sct#2221000221107 "Vaccine product containing only live attenuated Human alphaherpesvirus 3 antigen (medicinal product)"
* $sct#836498007+836388000 "Vaccine product containing Mumps orthorubulavirus antigen (medicinal product) + Vaccine product containing Rubella virus antigen (medicinal product)"
* $sct#871729003+836380007+601000221108+863911006+836374004+871871008 "Vaccine product containing only Corynebacterium diphtheriae antigen (medicinal product) + Vaccine product containing Haemophilus influenzae type B antigen (medicinal product) + Vaccine product containing Bordetella pertussis antigen (medicinal product) + Vaccine product containing Clostridium tetani antigen (medicinal product) + Vaccine product containing Hepatitis B virus antigen (medicinal product) + Vaccine product containing only Neisseria meningitidis serogroup A and C antigens (medicinal product)"
* $sct#871891001 "Vaccine product containing only acellular Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Hepatitis B virus and inactivated whole Human poliovirus antigens (medicinal product)"
* $sct#871729003+836380007+601000221108+863911006+836374004 "Vaccine product containing only Corynebacterium diphtheriae antigen (medicinal product) + Vaccine product containing Haemophilus influenzae type B antigen (medicinal product) + Vaccine product containing Bordetella pertussis antigen (medicinal product) + Vaccine product containing Clostridium tetani antigen (medicinal product) + Vaccine product containing Hepatitis B virus antigen (medicinal product)"
* $sct#871804001 "Vaccine product containing only Hepatitis A virus and Salmonella enterica subspecies enterica serovar Typhi antigens (medicinal product)"
* $sct#871895005 "Vaccine product containing only Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Haemophilus influenzae type B and Hepatitis B virus and Human poliovirus antigens (medicinal product)"
* $sct#871806004 "Vaccine product containing only Haemophilus influenzae type B and Hepatitis B virus antigens (medicinal product)"
* $sct#871729003+836374004+863911006 "Vaccine product containing only Corynebacterium diphtheriae antigen (medicinal product) + Vaccine product containing Hepatitis B virus antigen (medicinal product) + Vaccine product containing Clostridium tetani antigen (medicinal product)"
* $sct#871887006 "Vaccine product containing only Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Haemophilus influenzae type B and Human poliovirus antigens (medicinal product)"
* $sct#863911006+836374004+601000221108+836381006 "Vaccine product containing Clostridium tetani antigen (medicinal product) + Vaccine product containing Hepatitis B virus antigen (medicinal product) + Vaccine product containing Bordetella pertussis antigen (medicinal product) + Vaccine product containing Corynebacterium diphtheriae antigen (medicinal product)"
* $sct#836380007+1031000221108 "Vaccine product containing Haemophilus influenzae type B antigen (medicinal product) + Vaccine product containing Human poliovirus antigen (medicinal product)"
* $sct#871729003+836388000+863911006 "Vaccine product containing only Corynebacterium diphtheriae antigen (medicinal product) + Vaccine product containing Rubella virus antigen (medicinal product) + Vaccine product containing Clostridium tetani antigen (medicinal product)"
* $sct#871878002 "Vaccine product containing only Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Human poliovirus antigens (medicinal product)"
* $sct#871837004 "Vaccine product containing only Clostridium tetani and Corynebacterium diphtheriae and Human poliovirus antigens (medicinal product)"
* $sct#871908002 "Vaccine product containing only Human alphaherpesvirus 3 and Measles morbillivirus and Mumps orthorubulavirus and Rubella virus antigens (medicinal product)"
* $sct#836382004+836388000 "Vaccine product containing Measles morbillivirus antigen (medicinal product) + Vaccine product containing Rubella virus antigen (medicinal product)"
* $sct#871831003 "Vaccine product containing only Measles morbillivirus and Mumps orthorubulavirus and Rubella virus antigens (medicinal product)"
* $sct#836498007+836382004 "Vaccine product containing Mumps orthorubulavirus antigen (medicinal product) + Vaccine product containing Measles morbillivirus antigen (medicinal product)"
* $sct#871803007 "Vaccine product containing only Hepatitis A and Hepatitis B virus antigens (medicinal product)"
* $sct#871826000 "Vaccine product containing only Clostridium tetani and Corynebacterium diphtheriae antigens (medicinal product)"
* $sct#836398006+836380007 "Vaccine product containing Streptococcus pneumoniae antigen (medicinal product) + Vaccine product containing Haemophilus influenzae type B antigen (medicinal product)"
* $sct#836500008 "Vaccine product containing only Haemophilus influenzae type B and Neisseria meningitidis serogroup C antigens (medicinal product)"
* $sct#836380007+601000221108 "Vaccine product containing Haemophilus influenzae type B antigen (medicinal product) + Vaccine product containing Bordetella pertussis antigen (medicinal product)"
* $sct#836383009+836390004 "Vaccine product containing Vibrio cholerae antigen (medicinal product) + Vaccine product containing Salmonella enterica subspecies enterica serovar Typhi antigen (medicinal product)"
* $sct#836378001 "Vaccine product containing Japanese encephalitis virus antigen (medicinal product)"
* $sct#836403007 "Vaccine product containing Tick-borne encephalitis virus antigen (medicinal product)"
* $sct#871738001 "Vaccine product containing only live attenuated Mumps orthorubulavirus antigen (medicinal product)"
* $sct#1031000221108 "Vaccine product containing Human poliovirus antigen (medicinal product)"
* $sct#836387005 "Vaccine product containing Rotavirus antigen (medicinal product)"
* $sct#836393002 "Vaccine product containing Rabies lyssavirus antigen (medicinal product)"
* $sct#836495005 "Vaccine product containing Human alphaherpesvirus 3 antigen (medicinal product)"
* $sct#836389008 "Vaccine product containing Vaccinia virus antigen (medicinal product)"
* $sct#836379009 "Vaccine product containing Human papillomavirus antigen (medicinal product)"
* $sct#836385002 "Vaccine product containing Yellow fever virus antigen (medicinal product)"
* $sct#836388000 "Vaccine product containing Rubella virus antigen (medicinal product)"
* $sct#836382004 "Vaccine product containing Measles morbillivirus antigen (medicinal product)"
* $sct#836375003 "Vaccine product containing Hepatitis A virus antigen (medicinal product)"
* $sct#836374004 "Vaccine product containing Hepatitis B virus antigen (medicinal product)"
* $sct#836377006 "Vaccine product containing Influenza virus antigen (medicinal product)"
* $sct#836390004 "Vaccine product containing Salmonella enterica subspecies enterica serovar Typhi antigen (medicinal product)"
* $sct#836402002 "Vaccine product containing live attenuated Mycobacterium bovis antigen (medicinal product)"
* $sct#863911006 "Vaccine product containing Clostridium tetani antigen (medicinal product)"
* $sct#836398006 "Vaccine product containing Streptococcus pneumoniae antigen (medicinal product)"
* $sct#840549009 "Vaccine product containing Yersinia pestis antigen (medicinal product)"
* $sct#601000221108 "Vaccine product containing Bordetella pertussis antigen (medicinal product)"
* $sct#836401009 "Vaccine product containing Neisseria meningitidis antigen (medicinal product)"
* $sct#836380007 "Vaccine product containing Haemophilus influenzae type B antigen (medicinal product)"
* $sct#836381006 "Vaccine product containing Corynebacterium diphtheriae antigen (medicinal product)"
* $sct#836383009 "Vaccine product containing Vibrio cholerae antigen (medicinal product)"
* $sct#836384003 "Vaccine product containing Bacillus anthracis antigen (medicinal product)"